### ISSUE TITLE
packages.sh will add dups of LLVM repo

### ISSUE THREAD

**Issue by pervazea** [cmu-db/peloton#1067]
If you run packages.sh more than once, it will add the LLVM repo into /etc/apt/sources.list each time, without first checking if it is present.

This causes apt to complain about having duplicate sources.

**Comment by crd477** [comment]
On 2018-01-18 10:39, pervazea wrote:
> If you run packages.sh more than once, it will add the LLVM repo into 
> /etc/apt/sources.list each time, without first checking if it is present.
> 
> This causes apt to complain about having duplicate sources.
> 

You could back out the change to line 29 in 
abf963389e05fdbe99f52de801dccda230876619 to fix this.

If you do that, please let me know because software-properties-common 
needs to be explicitly added as a prerequisite to some of the Docker 
images in Jenkins before packages.sh is run.

Alternatively, you could just ignore apt's complaints.  Is it actually 
common that packages.sh would get run more than once?

-- 
     -Chad

**Comment by pervazea** [comment]
It is reasonable to run packages.sh again. If the required packages change, or are supplemented, I expect the preferred way is to simply re-run packages.sh.

I think the correct approach here, would be to check if the content is in sources.list, and add only if it is not. I'm not an expert in sh, so don't have a recipe to suggest offhand. On ignoring apt's complaints. Not sure this is safe. Apt is trying to help here... so even if safe, this seems inadvisable.
