### ISSUE TITLE
Peloton connects to nonexistent database

### ISSUE THREAD

**Issue by schedutron** [cmu-db/peloton#1164]
In the `psql` client, if I type `\c foo`, where the database `foo` has not yet been created, Peloton shows a success message:

```
binaryBoy=# \c foo;
psql (10.1, server 9.5devel)
You are now connected to database "foo" as user "binaryBoy".
foo=# 
```

Later, if we, say, try to create a table, then it shows an error:

```
foo=# create table bar(id int);
Can't find Database foo to create table
foo=# 
```

**Comment by eribeiro** [comment]
Hi @schedutron, it's not my intention to step on your toes, so I am leaving this here as a patch file you can git apply and see if it solves what you need or at least guide you through a direction. I dunno the trivial test I wrote is working, for example. But it seems to have solved the issue. /cc @apavlo

[1164.txt](https://github.com/cmu-db/peloton/files/1825796/1164.txt)

Please, let me know what you both think, because it's not my intention to create a PR to address this at first, as you are in charge.

Cheers!

**Comment by eribeiro** [comment]
Oh, and the "3D000" code you see in the patch came from here: https://www.postgresql.org/docs/10/static/errcodes-appendix.html and I could confirm via Wireshark on a psql connection to Postgres.

**Comment by pmenon** [comment]
I think #1224 supersedes this. Closing for now.
