### ISSUE TITLE
Optimize non-inlined value processing

### ISSUE THREAD

**Issue by jarulraj** [cmu-db/peloton#13]
Store the non-inlined data in a manner optimized for faster comparisons. For instance, a long string can be represented by its start and end letters and a pointer to the actual string.

**Comment by jarulraj** [comment]
Let's do this later.

**Comment by tomasic** [comment]
if it is "do this later", don't we just assign the ticket to the "future
work" milestone, instead of closing it? (thus we have a way to track future
work ideas)

On Thu, Dec 31, 2015 at 10:19 AM, Joy Arulraj <notifications@github.com>
wrote:

> Let's do this later.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cmu-db/peloton/issues/13#issuecomment-168215970>.
>



-- 
Anthony Tomasic
Senior Systems Scientist
Language Technologies Institute
Carnegie Mellon University
http://ideate.cmu.edu/graduate-programs-research/emerging-media/
<http://ideate.cmu.edu/graduate-programs-research/emerging-media/>
http://www.tiramisutransit.com
*http://mcds.cs.cmu.edu <http://mcds.cs.cmu.edu>*
http://www.cs.cmu.edu/~tomasic

**Comment by jarulraj** [comment]
Yes, that makes sense. I have reopened the issue.

**Comment by jarulraj** [comment]
This idea won't work when we add support for collations.
