### ISSUE TITLE
jemalloc is not linked correctly

### ISSUE THREAD

**Issue by yingjunwu** [cmu-db/peloton#220]
jemalloc is not working for now. One solution is that we can force users to preload jemalloc. This makes sense as some users may prefer some other scalable memory allocation libraries (e.g., tcmalloc, hoard) rather than jemalloc.

**Comment by ranxian** [comment]
I will take a look on this

**Comment by ranxian** [comment]
The basic problem is that the way dynamic library dependencies are resolved is kind of BFS way. For example, `app` depends on `liba.so`, `liba.so` depends on `libjemalloc.so`. In either `app` or `liba.so`, `libc` will be linked, but `liba.so` links `libjemalloc.so` first then `libc`.

When the dependencies of `app` get resolved, it will first resolve its **directly** depended libraries: `liba.so` and `libc` in this case. Then resolve its direct dependencies' dependency: in this case `libjemalloc.so` for `liba.so`. So now you see how `libc` will be loaded earlier than `libjemalloc.so`.

In our case, `app` is `peloton`, `ycsb`, .... `liba.so` is `libpeloton.so`. The way that I'm going to solve this is instead of linking `libpeloton.so` with `libjemalloc.so`, I will link each individual binary (`peloton`, `ycsb`, ...) with `libjemalloc`.
@yingjunwu @jarulraj  @apavlo

**Comment by ranxian** [comment]
There are two solutions for this problem:

* The one I posted above. Cons: `libpeloton.so` is no longer the only object file any Peloton application will need, they will also need to link against `libjemalloc.so`

* Use `PRELOAD_LIB=/path/to/jemalloc`. By doing this we achieve the same goal, and we don't even need to include jemalloc's headers, and don't need to add it as a compile time dependencies. Another benefit is that we can replace the underlying mem allocator by changing jemalloc to another one and do no modification to the code base. Cons: we will not be enforcing the use of jemalloc at compile time, need to remind users to do the `PRELOAD_LIB` trick.

**Comment by ranxian** [comment]
@jarulraj @apavlo Please provide some design/architect thoughts, which approach is more desired?

**Comment by yingjunwu** [comment]
1. I think in your example, you did not mention the dependency of libc.probably what you mean is that liba.so depends on both libjemalloc.so and libc.

2. I think even in the first solution, we don't need to include jemalloc's header.

3. Have you tried the first solution? I attempted to adopt the first solution by modifying the current cmakefile but failed.

**Comment by apavlo** [comment]
Is it easier if we remove the YCSB shared library? 

I agree with @yingjunwu that I like solution #1.

**Comment by jarulraj** [comment]
You can check out the usage pattern in Chromium.

https://github.com/adobe/chromium/blob/cfe5bf0b51b1f6b9fe239c2a3c2f2364da9967d7/base/allocator/allocator_shim.cc

**Comment by ranxian** [comment]
@jarulraj in the Chromium case, they are explicitly calling the prefixed version `je_malloc` instead of `malloc` (https://github.com/adobe/chromium/blob/cfe5bf0b51b1f6b9fe239c2a3c2f2364da9967d7/base/allocator/allocator_shim.cc#L118). I guess we may prefer to still use `malloc` here

**Comment by ranxian** [comment]
@yingjunwu 

1. Yes. libc is anyway depended by either `libpeloton.so` or `peloton`, it will be very hacky not to link against libc
2. That is correct, if we are just using standard mem allocator function, not including `jemalloc` header is fine.
3. trying now

**Comment by ranxian** [comment]
@apavlo 
I'm not sure what do you mean, basically `libpeloton.so` is linked by `peloton`, `ycsb`, `tpcc`, etc. We don't really have a `ycsb` shared lib.

**Comment by ranxian** [comment]
@yingjunwu you are right, I tried the first approach but not work. This is because `bin/peloton` does not use `malloc` directly so when it gets linked the `-ljemalloc` flag is ignored. I need to add a link flag `-Wl,--no-as-needed` to force link against jemalloc.

Here is the result

![image](https://cloud.githubusercontent.com/assets/1311188/18227344/8b3b1490-71ef-11e6-854b-f9067e766802.png)
