### ISSUE TITLE
Drop index executor

### ISSUE THREAD

**Issue by eric-haibin-lin** [cmu-db/peloton#285]
Currently drop executor can only drop a table. Dropping an index is not implemented yet. 

https://github.com/cmu-db/peloton/blob/master/src/executor/drop_executor.cpp#L39

**Comment by apavlo** [comment]
@AngLi-Leon This is another good task to start with. We can discus tomorrow if you want.

**Comment by AngLi-Leon** [comment]
Cool!

**Comment by AngLi-Leon** [comment]
I am starting to working on this. The first issue is that, Peloton currently treats `DROP INDEX index_name` same as dropping table and we should change the new parser to follow the right syntax. The second issue is that Postgres does not allow same index name within a schema (see https://www.postgresql.org/docs/9.6/static/sql-dropindex.html and http://stackoverflow.com/questions/26997441/why-cant-two-tables-have-an-index-of-the-same-name), which also means that we can drop an index even without a table name. This could also mean we should make modification to the new catalog and use `index_name` rather than` index_name` with `table_oid` as unique internally.

**Comment by dasdipanjan04** [comment]
Hi,

I am kinda new to opensource-contribution. Can I work on this issue?
Sorry for asking such a silly question.

Thanks
Dipanjan

**Comment by apavlo** [comment]
@dasdipanjan04 I don't think anybody is working on it at the moment. So if you want to work on it, then go for it. Keep us posted with your progress.

The tricky thing about this one is that it needs to work with @ChTimTsubasa's new `StatementCache` in #951. We will merge that in the next few days. When the txn that drops an index commits, you need to go through the `StatementCache` and invalidate any query plan that references that index.

Check with @mengranwo + @poojanilangekar on whether we correctly clean up the index's memory in the garbage collector after we know that know other txn could access the index.

**Comment by dasdipanjan04** [comment]
@apavlo thanks for the response and for the related issue. 
@mengranwo and @poojanilangekar please let me know about **correctly cleaning up the index's memory**.

**Comment by dasdipanjan04** [comment]
@apavlo I have implemented the DropIndex with one Test case in drop_test and will see what happens after #951 merge. Please pardon me if I have understood/did anything wrong.

**Comment by dasdipanjan04** [comment]
Works fine after implementing the requested changes by @poojanilangekar .
