### ISSUE TITLE
configurable thread count

### ISSUE THREAD

**Issue by yingjunwu** [cmu-db/peloton#347]
The current implementation set the number of threads for transaction processing to `std::thread::hardware_concurrency()` by default. This may not be correct. We should preserve some threads for garbage collection and logging. Also, the system must know the number of threads assigned for each component (e.g., transaction processing, garbage collection, and logging) prior to execution. To solve this problem, I introduced some variables in `types.h` and users should set these variables when booting Peloton.

**Comment by apavlo** [comment]
We should talk about this with @malin1993ml. It's good that this parameter is no longer hardcoded, but we want to be able to make it dynamic so that we can tweak it at runtime. This is part of a larger theme of having all of the configuration knobs dynamic so that Lin's work can change it.

This is a good start though.

**Comment by malin1993ml** [comment]
Sounds good. We can talk about this at some point.
