### ISSUE TITLE
Fix B+Tree Index or Remove it

### ISSUE THREAD

**Issue by apavlo** [cmu-db/peloton#453]
I think that we should keep the `BTreeIndex` around in case we need something more simple than the `BwTreeIndex`. But it currently does not work with any of our test cases. I think that @jarulraj also has a `SkipListIndex` somewhere too.

We should either fix these indexes and re-enable them in `IndexPerformanceTests` or remove them.

**Comment by apavlo** [comment]
Here are the errors if you re-enable `INDEX_TYPE_BTREE` in the `IndexPerformanceTests`:

```
/home/pavlo/Documents/Peloton/Github/peloton/test/performance/index_performance_test.cpp:288: Failure
Value of: location_ptrs.size()
  Actual: 0
Expected: num_thread * num_key
Which is: 1048576
[INFO ] [test/performance/index_performance_test.cpp:293:TestIndexPerformance()] 2017-01-03 09:46:47 - InsertTest1 :: Type=BTREE; Duration=0.21
[INFO ] [test/performance/index_performance_test.cpp:314:TestIndexPerformance()] 2017-01-03 09:46:47 - DeleteTest1 :: Type=BTREE; Duration=0.79
/home/pavlo/Documents/Peloton/Github/peloton/test/performance/index_performance_test.cpp:330: Failure
Value of: location_ptrs.size()
  Actual: 0
Expected: num_thread * num_key
Which is: 1048576
[INFO ] [test/performance/index_performance_test.cpp:335:TestIndexPerformance()] 2017-01-03 09:46:47 - InsertTest2 :: Type=BTREE; Duration=1.02
[INFO ] [test/performance/index_performance_test.cpp:356:TestIndexPerformance()] 2017-01-03 09:46:48 - DeleteTest :: Type=BTREE; Duration=1.74
[  FAILED  ] IndexPerformanceTests.BTreeMultiThreadedTest (1746 ms)
```

**Comment by wangziqi2013** [comment]
The B+Tree index could be used as a backup plan, in a sense that if the fanout for a key in a table is too large (e.g. > 100) then BwTree has miserable performance on Insert() and Delete() because it has to keep operations atomic on a large set of records. In this case maybe using a B+Tree might be beneficial. This could be made as a knob for tuning and let the user make decision

**Comment by apavlo** [comment]
Right, but we would have to modify it to make it concurrent.

**Comment by tomasic** [comment]
Large fan out is important in disk based b tree indexing. That's because
processing the index page is cheap compared to a disk read. (100th the
cost). So the equation was log(n,b) disk reads.

But for memory based indexes you now have to count memory cycles. And
processing an index node takes cycles also. So it is now something like
log(n,b)*b memory reads.
