### ISSUE TITLE
Add CLion Instructions to Wiki

### ISSUE THREAD

**Issue by apavlo** [cmu-db/peloton#503]
The kids are asking about how to use CLion instead of Eclipse. We need to update our documentation.

Hopefully this should be easy. I am willing to be the first guinea pig.

**Comment by apavlo** [comment]
@jessesleeping Let me know if you have time to do this. You can work with @AllisonWang to test this.

**Comment by hanfeisun** [comment]
I'm not sure whether there is an easy/built-in way to develop and debug with Clion on OSX. 

I just found a thread for Clion about remote project development support: https://youtrack.jetbrains.com/issue/CPP-744

And it seems the issue is still open.

**Comment by AllisonWang** [comment]
@AngLi-Leon and I were able to add all dependencies but we still failed to build the project on OSX even after we compiled the project using gcc instead of clang. 
So one way to use CLion for now is to clone peloton inside the shared folder of VirtualBox `/vagrant`, and open the project on mac using CLion while compiling/building/testing the project inside the VM.

**Comment by apavlo** [comment]
@AllisonWang What was the compilation error?

**Comment by AllisonWang** [comment]
@apavlo I am thinking if this error is related to protobuf syntax version.
```
/Users/Allison/Desktop/peloton/src/include/common/logger.h:109:43: error: 
format '%lu' expects argument of type 'long unsigned int', but argument 4 has 
type 'google::uint64 {aka long long unsigned int}' [-Werror=format=]
   ::fprintf(LOG_OUTPUT_STREAM, __VA_ARGS__);
```

**Comment by apavlo** [comment]
That's our code. That's weird. I think this should be fixable.

**Comment by poojanilangekar** [comment]
@AngLi-Leon has fixed it. https://github.com/cmu-db/peloton/wiki/Develop-and-Debug-with-CLion-on-macOS
