### ISSUE TITLE
Invoke EXTRACT function correctly

### ISSUE THREAD

**Issue by hzxa21** [cmu-db/peloton#637]
The Postgres parser parses the EXTRACT function into date_part function so now Peloton cannot invoke the EXTRACT function correctly.
``` sql
postgres=# create table a(t timestamp);
create table a(t timestamp) 0
postgres=# insert into A values('2017-01-02 12:13:14.999999+00');
insert into A values('2017-01-02 12:13:14.999999+00') 1
postgres=# select extract(century from t) from a;
function date_part not found.
```

date_part should be made as an alias to EXTRACT function and the parser should be modified to feed the right DatePartType into the arguments of the EXTRACT function.
https://github.com/cmu-db/peloton/blob/master/src/expression/date_functions.cpp#L33
https://github.com/cmu-db/peloton/blob/master/src/parser/postgresparser.cpp#L411
https://github.com/cmu-db/peloton/blob/master/src/catalog/catalog.cpp#L904

**Comment by malin1993ml** [comment]
Hi @pbollimp and @sivaprasadsudhir,

What's the status of the EXTRACT implementation? As we discussed earlier, it turned out that it's not feasible to convert the date_part string to DatePartType at bind time. So we just need to do the string comparison inside the function at runtime. I remember you guys pretty much already finished the implementation? If so, can you wrap up and submit a PR?
