### ISSUE TITLE
Remove Semi-Colon Hack

### ISSUE THREAD

**Issue by apavlo** [cmu-db/peloton#681]
This issue supplants #422.

We currently cannot support queries that have a semi-colon in them. The reason is because the `PacketManager::ExecQueryMessage` splits every incoming query by semi-colons:

https://github.com/cmu-db/peloton/blob/master/src/wire/packet_manager.cpp#L302

This was originally meant to support queries with multiple statements in them:

```sql
SELECT 1; SELECT 2;
```

But this will cause problems if there is a semi-colon **in** the query itself:

```sql
SELECT * FROM foo WHERE col = 'hello;world';
```

-----------------------

We need to refactor the `PacketManager` and `TrafficCop` to be able to handle multi-statement queries. The key thing is that the new SQL parser will return multiple parse trees if there are multiple statements. So we don't need to parse semi-colons manually anywhere in our own code.

Here is a rough outline of what I think we need to do:

1. The first thing to change is obviously to remove the split in `PacketManager::ExecQueryMessage()`. 

   https://github.com/cmu-db/peloton/blob/master/src/wire/packet_manager.cpp#L302

   Then remove the **for** loop in this function. It should not be iterating over multiple queries because it does not know that there are multiple queries.

   https://github.com/cmu-db/peloton/blob/master/src/wire/packet_manager.cpp#L316

2. Refactor `TrafficCop::ExecuteStatement()` to return back an **std::vector** of query results. This is instead of passing the output result buffers by reference as function arguments. Combine the following four items into a object (you can use a name like `StatementResult`):

   https://github.com/cmu-db/peloton/blob/master/src/wire/packet_manager.cpp#L319

   You'll also want to add the `ResultType` status code that `TrafficCop::ExecuteStatement()` currently returns as the function result into the `StatementResult` object.

3. Here's where things get tricky. `TrafficCop::ExecuteStatement()` calls `TrafficCop::PrepareStatement()`.

   https://github.com/cmu-db/peloton/blob/master/src/tcop/tcop.cpp#L149

   This function is where the `TrafficCop` passes the query to the SQL parser:

   https://github.com/cmu-db/peloton/blob/master/src/tcop/tcop.cpp#L286

   I don't know what happens here if there are multiple statements in the query (@haojin2?). The **for** loop at the URL below looks like we can handle it right now:

   https://github.com/cmu-db/peloton/blob/master/src/tcop/tcop.cpp#L299

   But I don't know why there could be multiple statements but then it looks like we are still assuming in the rest of the code that there is only one. So this means that we are going to need to change `TrafficCop::PrepareStatement()` to return multiple `Statement` objects instead of just one.

   Hopefully these changes are localized and we don't have to make major changes in other parts of the code.

**Comment by ChTimTsubasa** [comment]
What we can do tomorrow @dengyuchenkit 
1. We may look into the code in PacketManager::ExecQueryMessage(), TrafficCop::ExecuteStatement() and TrafficCop::PrepareStatement() to see what are these pieces and other related functions are actually doing right now.
2. Do some initial changes on ExecQueryMessage and ExecuteStatement first and see if this would work.

**Comment by ChTimTsubasa** [comment]
@dengyuchenkit  and I changed PacketManager::ExecQueryMessage() by deleting the split() line and for loop. The running result looks good: it can now support multiple queries and queries that with ';' in it. One sample test is as follow:

postgres=# create table foo(info varchar(10));
create table foo(info varchar(10)); 0
postgres=# select * from foo;
 info 
------
(0 rows)

postgres=# insert into foo values ('2');
insert into foo values ('2'); 1
postgres=# select * from foo;
 info 
------
 2
(1 row)

postgres=# insert into foo values ('2;');
insert into foo values ('2;'); 1
postgres=# select * from foo;
 info 
------
 2
 2;
(2 rows)

postgres=# insert into foo values ('3;');select * from foo;
insert into foo values ('3;'); 1
 info 
------
 2
 2;
 3;
(3 rows)

We haven't done the TrafficCop::ExecuteStatement() refactor yet and we will further look at the code tomorrow and see if it is necessary to do so. Right now we had a glance into only some of the code.

**Comment by apavlo** [comment]
@dengyuchenkit @ChTimTsubasa This is a good start. Be sure to use this issue # in your commit messages so they are automatically linked to this report. 

https://github.com/blog/957-introducing-issue-mentions

**Comment by apavlo** [comment]
@dengyuchenkit @ChTimTsubasa Any update on this?

**Comment by dengyuchenkit** [comment]
@ChTimTsubasa and I found that when the user inputs two query in one line, the EventHandler(https://github.com/cmu-db/peloton/blob/master/src/wire/libevent_callbacks.cpp#L66) is triggered twice, one for each query. Before the queries go to ExecQueryMessage(https://github.com/cmu-db/peloton/blob/master/src/wire/packet_manager.cpp#L297), they are split. We are thinking if the frontend in postgres has processed the queries. We do not know what frontend gives back to the backend in peloton yet.

**Comment by ChTimTsubasa** [comment]
This is a test we did:
I insert the LOG_DEBUG code into PacketManager::ExecQueryMessage and PacketManager::ProcessPacket
if typing a multi-statement line like:
insert into foo values(2, 100);insert into foo values(5, 200);insert into foo values(3,100);

The result shows:
/home/tim/Downloads/2056524122.jpg

Where the PacketManager::ProcessPacket is called three times and each time the query that passed through the packet has been split.

**Comment by ChTimTsubasa** [comment]
**We had done some test and got the following observation:**
1) When psql is used in terminal, the client actually splits and parses the statement into multiple packets and sent them separately in SIMPLE_QUERY_COMMAND message type. Each packet will triggers one event handler (https://github.com/cmu-db/peloton/blob/master/src/wire/libevent_callbacks.cpp#L66) and finally get handled in PacketManager::ExecQueryMessage (https://github.com/cmu-db/peloton/blob/adf8745dadb2616a0e7cc9939d9d54801be0d1af/src/wire/packet_manager.cpp#L894). So simply delete the loop and the split() line should work fine for valid but multi-query user input.

2) When JDBC is used, there is only one packet with multiple queries being sent to peloton application. Although triggering the event handler only once, but this packet has message type PARSE_COMMAND and would be handled by PacketManager::ExecParseMessage (https://github.com/cmu-db/peloton/blob/adf8745dadb2616a0e7cc9939d9d54801be0d1af/src/wire/packet_manager.cpp#L363). The line (https://github.com/cmu-db/peloton/blob/c975cde048b78c29c992fc06de6cdf9e18f37f19/src/wire/marshal.cpp#L96) in the GetStringToken(pkt, query_string) would split the packet content by '\0', and therefore automatically split the queries in the packet since they separated by 8 '\0'. We used the Multiple_Test()
 in (https://github.com/cmu-db/peloton/blob/master/script/testing/jdbc/src/PelotonTest.java#L229) as well as writing the following code. They both show the same result.
`Statement stmt = conn.createStatement();
    stmt.execute(INSERT_A_1 + INSERT_A_1);`

3) When JDBC is used, the way in which current code handles splitting is probably not very efficient because it moves its packet pointer only by 1 '\0' character each time and then needs to transit at least two states to move the pointer again. That means it should transit 16 states to actually move from one query to another since the two queries are separated by 8 '\0'.

**Simply conclude:**
1) Current modification works when typing valid but multi-query line, but fails in some of the invalid input such as '  ;' or 'SELECT;', as mentioned in issue #680. Should we first make a pull request fixing this issue #681 first and then working on #680?

2) Not sure if we need to fix observation 3?

**Comment by apavlo** [comment]
Good finds. Send a PR for #681 first. There is a bunch of networking layer fixes in #672 that we should merge first before you look into observation 3.

**Comment by prashasthip** [comment]
I was testing out the current Peloton code for creating a UDF and the issue is still present.

Command: 
```
CREATE OR REPLACE FUNCTION increment(i integer) RETURNS integer AS $$
        BEGIN
                RETURN i + 1;
        END;
$$ LANGUAGE plpgsql;
```

Error Message
<img width="749" alt="screen shot 2017-09-18 at 5 14 32 pm" src="https://user-images.githubusercontent.com/11154612/30565034-e3ae2eac-9c94-11e7-8035-686dd749a7df.png">

@dengyuchenkit @apavlo

**Comment by ChTimTsubasa** [comment]
@prashasthip 
Which method are you using to access Peloton? PSQL or JDBC?

**Comment by dengyuchenkit** [comment]
@ChTimTsubasa One example is that we create a UDF like this https://www.postgresql.org/docs/9.1/static/sql-createfunction.html through terminal. @prashasthip The problem is that we didn't let parser to handle it right now. To solve it we will get rid of the hacky preprocessing to the network packet before it is sent to the parser.

**Comment by ChTimTsubasa** [comment]
@prashasthip I have discussed with @dengyuchenkit and testes around using Wireshark. 

Basically, if you are accessing using PSQL, the PSQL client would send this as a whole packet to Peloton, without truncating into pieces separated by semicolumn.

In the network layer, we are doing no preprocessing for any SQL line since the PSQL client has already handled this problem.

The problem is from the parser since it does not support such kind of operation. Specifically, Peloton has no node-transform function like CreateFunctionStmt yet. 

If you dive deep into the code, you can find that the exception is actually thrown from (https://github.com/cmu-db/peloton/blob/e4023183d26117f2ef77d7ede3ea2dc6803e5d8a/src/parser/postgresparser.cpp#L1311),
 and the type code 723 is T_CreateFunctionStmt(https://github.com/cmu-db/peloton/blob/45c2c75493049796bf2db82d001a4ac73f86e8c1/third_party/libpg_query/nodes.h#L303)
