### ISSUE TITLE
Request regarding Proejct #2 of the 15721 course

### ISSUE THREAD

**Issue by fadgan** [cmu-db/peloton#786]
Dear friends,
Is there a drop-in replacement/sample of the files that are the only ones that needs to be modified to run Project 2 from the 15721 course?
`/src/index/skiplist.cpp,
/src/include/index/skiplist.h,
/src/index/skiplist_index.cpp,
/src/include/index/skiplist_index.h`
and the corresponding index testing suit file
`/test/index/skiplist_index_test.cpp`

Thanks beforehand.

**Comment by apavlo** [comment]
Are you asking what files you need to modify to complete Project 2 or are you looking for the solution?

**Comment by fadgan** [comment]
Nope, not the files that need to be modified because the list of these files are already there in the project 2 specification and in my first post. I'm asking for a sample solution to go through. 
These files currently contain only skeleton but not the implementations. 
So, I was wondering if you could upload a solution !?

**Comment by apavlo** [comment]
Sorry, we're not making the solution available because we may use the same assignment next year. There are a ton of resources on-line how to build a skip list. There is nothing special about this project.

You can also get an idea on how certain things work by looking at our Bw-Tree implementation:

https://github.com/cmu-db/peloton/blob/master/src/include/index/bwtree.h
