### ISSUE TITLE
Add support for LLVM DISTINCT

### ISSUE THREAD

**Issue by apavlo** [cmu-db/peloton#825]
The LLVM engine does not support `DISTINCT`. The parser/planner already supports this, so you don't need to modify anything other than the LLVM engine. We need the following features for TPC-C:

1. `SELECT DISTINCT <col>`
2. `SELECT <AGGREGATE>(DISTINCT <col>)`

As always, try to follow the semantics of Postgres:

https://www.postgresql.org/docs/current/static/sql-select.html#sql-distinct

We don't need to support `DISTINCT ON (...)` right now.

@pmenon @seojungmin Can provide more guidance on where to add this new code. You should reuse the existing hash table in the LLVM engine.

**Comment by tcm-marcel** [comment]
The task is basically finished. 
However, there is a strange bug that appears when executing a query with several distinct AVG aggregations, that some of them return empty results. I wasn't able to find the cause yet, because it's happens somewhere in the dynamic execution and is very hard to debug. I will continue to find the problem.
