### ISSUE TITLE
Add Support for SSL Network Connections

### ISSUE THREAD

**Issue by apavlo** [cmu-db/peloton#845]
We currently do not support SSL connections. This means that you always have to disable SSL from the commandline. We need to integrate support for openssl in the system. We should follow the same configuration setup as [Postgres](https://www.postgresql.org/docs/9.6/static/ssl-tcp.html).

This was attempted before in #667 but the students working on it did not get very far. They hardcoded a bunch of paths for the Vagrant VM which is obviously incorrect:

https://github.com/cmu-db/peloton/blob/master/src/include/settings/settings.h#L46

We need coordinate with @ChTimTsubasa on this. I believe the issue is that the first packet that arrives from the client is the SSL handshake attempt, which I think causes problems in the current ProtocolHandler.

**Comment by ChTimTsubasa** [comment]
Concretely, this is because the first handshake to open (client send Version number and server response "YES") is done before ProtocolHandler is instantiated currently. Since sending a response back requires the participation of ProtocolHandler, this would cause SEG_FAULT.

In addition, such handshake looks specific to Postgres (MySQL uses a passive way to handle a new connection).

**Comment by pervazea** [comment]
This appears to be addressed by #926. If correct, we should close this.

**Comment by ChTimTsubasa** [comment]
This issue has been adressed
