### ISSUE TITLE
Support DATE type in parser

### ISSUE THREAD

**Issue by seojungmin** [cmu-db/peloton#852]
DATE type is not yet supported in parser.  

```
postgres=# create table test (a int, b date);
Exception Type :: Not implemented
Message :: Column DataType date not supported yet...

Column DataType date not supported yet...

postgres=#
```

**Comment by haojin2** [comment]
Which value type does date belong to? Timestamp?

**Comment by apavlo** [comment]
DATE is its own type. We added the TypeID

**Comment by haojin2** [comment]
I see, I'll add that to parser

**Comment by haojin2** [comment]
The CREATE side should not have any problems now, however when I'm testing on the INSERT side I found the following problems:
1) I cannot do something like: "INSERT INTO test VALUES(1, '2017-11-07');" because there's no cast from varchar to date.
2) I cannot do something like: "INSERT INTO test VALUES(1, '2017-11-07'::date);" because there's no support for T_TYPECAST in parser transformer yet.
3) I cannot do something like: "INSERT INTO test VALUES(1, TO_DATE('2017-11-07', 'YYYY-MM-DD'));" because there's no TO_DATE builtin function yet.
I guess to support insert into a table with date field we'll have to support at least one of the 3 things we need.

**Comment by seojungmin** [comment]
@haojin2 Can you list up which modules should support each problem that you mentioned, respectively?

**Comment by haojin2** [comment]
Hi Tony,
I think 1 & 3 should be implemented by some internal functions, I was working on the cast from varchar to date earlier but then moved on to the parallel LLVM project so it's still under construction. For 2 I think we should first provide support in parser transformer for TYPECAST and also implement TYPECAST for all types we have.
Hao
