### ISSUE TITLE
Error during linking of libpg_query library in third party  

### ISSUE THREAD

**Issue by pbollimp** [cmu-db/peloton#858]
Using the fingerprint function pg_query_fingerprint (after including "parser/pg_query.h") from within peloton in traffic_cop.cpp, gives the following error. 

> Undefined symbols for architecture x86_64:
>   "_list_head", referenced from:
>       __fingerprintNode in libpg_query.a(pg_query_fingerprint.o)
> ld: symbol(s) not found for architecture x86_64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> make[2]: *** [lib/libpeloton.0.0.5.dylib] Error 1
> make[1]: *** [src/CMakeFiles/peloton.dir/all] Error 2
> make: *** [all] Error 2

This problem is happening irrespective of the commit (checked till as far back as commit e3db8318dcdb3c5 )

**Comment by apavlo** [comment]
@pbollimp How do I recreate this problem?

**Comment by pbollimp** [comment]
@apavlo In traffic_cop.cpp, include "parser/pg_query.h" and in `TrafficCop::PrepareStatement()` after `BuildParseTree()` is called, add this code:
`LOG_INFO("Fingerprint: %s", pg_query_fingerprint(query_string.c_str()).hexdigest);`

**Comment by tcm-marcel** [comment]
The problem are definitions of list helper functions in `pg_list.h`, for which the define `PG_USE_INLINE` decides whether they get inlined or not. However, the file `c.h` from libpg_query in which the defines are managed is never used neither in peloton nor in libpg_query. 

I accidentally solved the problem by adding 3 defines in `third_party/libpg_query/pg_list.h` BUT then realized that both libpeloton.so and libpg_query.a changed, so peloton somewhere includes the `pg_list.h` from the third_party folder instead of the one in `include/parser/pg_list.h`. 

I think the best solution would be 
1. finding how (and where) the wrong header file gets included and then 
2. remove all function definitions from the `include/parser/pg_list.h` because they are not needed there anyway (only needed inside libpg_query.a)

the lines I added in `third_party/libpg_query/pg_list.h`:
```c
#define PG_USE_INLINE
#define STATIC_IF_INLINE inline
#define NULL (0)
```

**Comment by pbollimp** [comment]
Thanks for your help @tcm-marcel 
The change below fixes the issue when added to the three locations having pg_list.h
(Why are there 3 files? There seem to be no difference between them):
src/include/parser/pg_list.h
third_party/libpg_query/pg_list.h, 
third_party/libpg_query/src/postgres/include/nodes/pg_list.h

```
#ifndef PG_USE_INLINE
  #define PG_USE_INLINE
  #define STATIC_IF_INLINE static inline
  #ifndef NULL
    #define NULL (0)
  #endif
#endif
```
Now the linking is happening without any error in marcel's and siva's laptop, but I'm still getting the error. It is likely my local issue

**Comment by sandy20140407** [comment]
hi~
I met  same error message when I run the command 'make -j4'.
The step of cmake does well,no error.
I try to delete the file named libpeloton-proto.a in /mypath/peloton/script/installation/build/lib,and make again, but same error.

OS:macOS 10.13.1 (17B1003)
kernel:Darwin 17.2.0
Xcode Version 9.2 (9C40b)

```
[ 97%] Building CXX object src/CMakeFiles/peloton.dir/__/third_party/libcount/hll.cc.o
[ 97%] Building CXX object src/CMakeFiles/peloton.dir/__/third_party/libcount/hll_data.cc.o
[ 97%] Building CXX object src/CMakeFiles/peloton.dir/__/third_party/libcount/utility.cc.o
[100%] Linking CXX shared library ../lib/libpeloton.dylib
ld: library not found for -lssl
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [lib/libpeloton.0.0.5.dylib] Error 1
make[1]: *** [src/CMakeFiles/peloton.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by apavlo** [comment]
@sandy20140407 Switch to Xcode8: https://github.com/cmu-db/peloton/wiki/Develop-and-Debug-with-CLion-on-macOS

**Comment by pbollimp** [comment]
@sandy20140407 If you still get the link error, please apply this patch (you may need to remove prints and some unnecessary code in traffic_cop.cpp) and see if you still get the error. 
[link_error_fix.patch.zip](https://github.com/cmu-db/peloton/files/1598576/link_error_fix.patch.zip)

**Comment by sandy20140407** [comment]
Thanks for help @apavlo and @pbollimp .
I have changed Xcode 9 to Xcode 8,and apply that patch.but, the error is still when make -j4。
Maybe it's my computer's problem.I'll use another one to install.
I'll paste here if any message.

**Comment by pbollimp** [comment]
Thanks to @malin1993ml for resolving this issue by moving `#include "postgres.h"` from `third_party/libpg_query/src/pg_query_fingerprint.c` to the top of the file to link successfully. That will force that .c file to include the macro definition of `PG_USE_INLINE` from `postgres.h` first before including `pg_list.h` in which case, we can have a real definition instead of the extern declaration when without the macro.

This fix will be applied as part of #1076

**Comment by chenboy** [comment]
Hi, @pbollimp @malin1993ml I'm also hitting this error. But I called a different set of functions in the `libpg_query` package: `pg_query_parse_plpgsql()` and `pg_query_free_plpgsql_parse_result()`, so including the header only in `pg_query_fingerprint.c` won't work for me. I think a more general fix should be including this header in `third_party/libpg_query/pg_query.h`. What do you think of it?

**Comment by malin1993ml** [comment]
Hi @chenboy, so it's not about the .h file. It's about the .c file where the function you need is defined **(not declared)**. In your case, I think move `pg_query_internal.h` to the top of `pg_query_parse_plpgsql.c` would do it.

I don't know whether we should include `postgres.h` in `pg_query.h` because that basically will change the logic of the postgres parser. There may or may not be potential impact to other files. Whereas by changing the inclusion order in .c files, we're not really adding or removing headers files. And even though there might be a side effect, it's only restricted to that .c file.
